const residences = [
  {
    id: 1,
    sold: "yes",
    purchased_by: "Shahbaz Tariq",
    title: "Deluxe One Bed",
    size: "531",
    floor: "2nd Floor",
    number: "D1",
    type: "Apartment",
    image: "/images/dsa/residences/2nd_D1.PNG",
  },
  {
    id: 2,
    sold: "yes",
    purchased_by: "Muhammad Ashfaq",
    title: "Deluxe Studio",
    size: "353",
    floor: "2nd Floor",
    number: "DS",
    type: "Apartment",
    image: "/images/dsa/residences/2nd_DS.PNG",
  },
  {
    id: 3,
    sold: "yes",
    purchased_by: "Muhammad Ashraf",
    title: "Executive One Bed",
    size: "559",
    floor: "2nd Floor",
    number: "E1",
    type: "Apartment",
    image: "/images/dsa/residences/2nd_E1.PNG",
  },
  {
    id: 4,
    sold: "yes",
    purchased_by: "Ali Imran",
    title: "Executive Studio",
    size: "373",
    floor: "2nd Floor",
    number: "ES",
    type: "Apartment",
    image: "/images/dsa/residences/2nd_ES.PNG",
  },
  {
    id: 5,
    sold: "yes",
    purchased_by: "Jehad Afzal Khan",
    title: "Deluxe One Bed",
    size: "531",
    floor: "3rd Floor",
    number: "D1",
    type: "Apartment",
    image: "/images/dsa/residences/3rd_D1.PNG",
  },
  {
    id: 6,
    sold: "yes",
    purchased_by: "Muhammad Saeed",
    title: "Deluxe Studio",
    size: "353",
    floor: "3rd Floor",
    number: "DS",
    type: "Apartment",
    image: "/images/dsa/residences/3rd_DS.PNG",
  },
  {
    id: 7,
    sold: "no",
    purchased_by: "",
    title: "Executive One Bed",
    size: "559",
    floor: "3rd Floor",
    number: "E1",
    type: "Apartment",
    image: "/images/dsa/residences/3rd_E1.PNG",
  },
  {
    id: 8,
    sold: "yes",
    purchased_by: "Imran Bin Ali",
    title: "Executive Studio",
    size: "373",
    floor: "3rd Floor",
    number: "ES",
    type: "Apartment",
    image: "/images/dsa/residences/3rd_ES.PNG",
  },
  {
    id: 9,
    sold: "no",
    purchased_by: "",
    title: "Deluxe One Bed",
    size: "531",
    floor: "4th Floor",
    number: "D1",
    type: "Apartment",
    image: "/images/dsa/residences/4th_D1.PNG",
  },
  {
    id: 10,
    sold: "yes",
    purchased_by: "",
    title: "Deluxe Studio",
    size: "353",
    floor: "4th Floor",
    number: "DS",
    type: "Apartment",
    image: "/images/dsa/residences/4th_DS.PNG",
  },
  {
    id: 11,
    sold: "no",
    purchased_by: "",
    title: "Executive One Bed",
    size: "559",
    floor: "4th Floor",
    number: "E1",
    type: "Apartment",
    image: "/images/dsa/residences/4th_E1.PNG",
  },
  {
    id: 12,
    sold: "yes",
    purchased_by: "Amir Saeed",
    title: "Executive Studio",
    size: "373",
    floor: "4th Floor",
    number: "ES",
    type: "Apartment",
    image: "/images/dsa/residences/4th_ES.PNG",
  },
  {
    id: 13,
    sold: "no",
    purchased_by: "",
    title: "Deluxe One Bed",
    size: "531",
    floor: "5th Floor",
    number: "D1",
    type: "Apartment",
    image: "/images/dsa/residences/5th_D1.PNG",
  },
  {
    id: 14,
    sold: "no",
    purchased_by: "",
    title: "Deluxe Studio",
    size: "353",
    floor: "5th Floor",
    number: "DS",
    type: "Apartment",
    image: "/images/dsa/residences/5th_DS.PNG",
  },
  {
    id: 15,
    sold: "no",
    purchased_by: "",
    title: "Executive One Bed",
    size: "559",
    floor: "5th Floor",
    number: "E1",
    type: "Apartment",
    image: "/images/dsa/residences/5th_E1.PNG",
  },
  {
    id: 16,
    sold: "no",
    purchased_by: "",
    title: "Executive Studio",
    size: "373",
    floor: "5th Floor",
    number: "ES",
    type: "Apartment",
    image: "/images/dsa/residences/5th_ES.PNG",
  },
  {
    id: 17,
    sold: "no",
    purchased_by: "",
    title: "Deluxe One Bed",
    size: "531",
    floor: "6th Floor",
    number: "D1",
    type: "Apartment",
    image: "/images/dsa/residences/6th_D1.PNG",
  },
  {
    id: 18,
    sold: "no",
    purchased_by: "",
    title: "Deluxe Studio",
    size: "353",
    floor: "6th Floor",
    number: "DS",
    type: "Apartment",
    image: "/images/dsa/residences/6th_DS.PNG",
  },
  {
    id: 19,
    sold: "yes",
    purchased_by: "",
    title: "Executive One Bed",
    size: "559",
    floor: "6th Floor",
    number: "E1",
    type: "Apartment",
    image: "/images/dsa/residences/6th_E1.PNG",
  },
  {
    id: 20,
    sold: "no",
    purchased_by: "",
    title: "Executive Studio",
    size: "373",
    floor: "6th Floor",
    number: "ES",
    type: "Apartment",
    image: "/images/dsa/residences/6th_ES.PNG",
  },
  {
    id: 21,
    sold: "no",
    purchased_by: "",
    title: "Executive Shop",
    size: "905",
    floor: "1st Floor",
    number: "F1",
    type: "Shop",
    image: "/images/dsa/residences/1st_F1.PNG",
  },
  {
    id: 22,
    sold: "no",
    purchased_by: "",
    title: "Executive Office",
    size: "895",
    floor: "1st Floor",
    number: "F2",
    type: "Office",
    image: "/images/dsa/residences/1st_F2.PNG",
  },
  {
    id: 23,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "Executive Office",
    size: "873",
    floor: "Ground Floor",
    number: "G1",
    type: "Office",
    image: "/images/dsa/residences/ground_G1.PNG",
  },
  {
    id: 24,
    sold: "no",
    purchased_by: "",
    title: "Executive Shop",
    size: "832",
    floor: "Ground Floor",
    number: "G2",
    type: "Shop",
    image: "/images/dsa/residences/ground_G2.PNG",
  },
  {
    id: 25,
    sold: "yes",
    purchased_by: "Muhammad Ashfaq",
    title: "Executive Shop",
    size: "905",
    floor: "Lower Ground Floor",
    number: "LG1",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround_LG1.PNG",
  },
  {
    id: 26,
    sold: "no",
    purchased_by: "",
    title: "Executive Office",
    size: "895",
    floor: "Lower Ground Floor",
    number: "LG2",
    type: "Office",
    image: "/images/dsa/residences/lowerGround_LG2.PNG",
  },
];

export function getAllResidences() {
  return residences;
}

export function getResidenceById(id) {
  return residences.find((item) => item.id === id);
}

export function getResidenceByType(type) {
  return residences.filter((item) => item.type === type);
}
