const residences = [
  {
    id: 1,
    sold: "yes",
    purchased_by: "Surriya Perveen",
    title: "",
    size: "183",
    floor: "Lower Ground Floor",
    number: "1",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop01).png",
  },
  {
    id: 2,
    sold: "yes",
    purchased_by: "Imran Ali",
    title: "",
    size: "183",
    floor: "Lower Ground Floor",
    number: "2",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop02).png",
  },
  {
    id: 3,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "259",
    floor: "Lower Ground Floor",
    number: "3",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop03).png",
  },
  {
    id: 4,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "303",
    floor: "Lower Ground Floor",
    number: "4",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop04).png",
  },
  {
    id: 5,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "303",
    floor: "Lower Ground Floor",
    number: "5",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop05).png",
  },
  {
    id: 6,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "430",
    floor: "Lower Ground Floor",
    number: "6",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop06).png",
  },
  {
    id: 7,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "455",
    floor: "Lower Ground Floor",
    number: "7",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop07).png",
  },
  {
    id: 8,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "498",
    floor: "Lower Ground Floor",
    number: "8",
    type: "Shop",
    image: "/images/dsa/residences/lowerGround/LowerGround(Shop08).png",
  },
  {
    id: 9,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "662",
    floor: "Ground Floor",
    number: "1",
    type: "Office",
    image: "/images/dsa/residences/ground/GroundFloor(Office01).png",
  },
  {
    id: 10,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "721",
    floor: "Ground Floor",
    number: "2",
    type: "Office",
    image: "/images/dsa/residences/ground/GroundFloor(Office02).png",
  },
  {
    id: 11,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "",
    size: "788",
    floor: "Ground Floor",
    number: "3",
    type: "Office",
    image: "/images/dsa/residences/ground/GroundFloor(Office03).png",
  },

  {
    id: 12,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "260",
    floor: "1st Floor",
    number: "1",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop01).png",
  },
  {
    id: 13,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "281",
    floor: "1st Floor",
    number: "2",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop02).png",
  },
  {
    id: 14,
    sold: "yes",
    purchased_by: "Faryad Ali",
    title: "",
    size: "310",
    floor: "1st Floor",
    number: "3",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop03).png",
  },
  {
    id: 15,
    sold: "yes",
    purchased_by: "Faryad Ali",
    title: "",
    size: "330",
    floor: "1st Floor",
    number: "4",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop04).png",
  },
  {
    id: 16,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "490",
    floor: "1st Floor",
    number: "5",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop05).png",
  },
  {
    id: 17,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "518",
    floor: "1st Floor",
    number: "6",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop06).png",
  },
  {
    id: 18,
    sold: "no",
    purchased_by: "",
    title: "",
    size: "616",
    floor: "1st Floor",
    number: "7",
    type: "Shop",
    image: "/images/dsa/residences/first/FirstFloor(Shop07).png",
  },

  {
    id: 24,
    sold: "yes",
    purchased_by: "Ali Imran",
    title: "Studio Executive",
    size: "350",
    floor: "2nd Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioExecutive(350sqft).png",
  },
  {
    id: 22,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "Studio Deluxe",
    size: "369",
    floor: "2nd Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioDeluxe(369sqft).png",
  },
  {
    id: 23,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "391",
    floor: "2nd Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/second/StudioDeluxe(391sqft).png",
  },
  {
    id: 20,
    sold: "yes",
    purchased_by: "Muhammad Sadiq",
    title: "One Bed Executive",
    size: "575",
    floor: "2nd Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedExecutive(575sqft).png",
  },
  {
    id: 21,
    sold: "yes",
    purchased_by: "Shabaz Tariq",
    title: "One Bed Executive",
    size: "593",
    floor: "2nd Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedExecutive(593sqft).png",
  },
  {
    id: 19,
    sold: "yes",
    purchased_by: "Mujahid Farooqi",
    title: "One Bed Deluxe",
    size: "596",
    floor: "2nd Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/second/OneBedDeluxe(596sqft).png",
  },

  {
    id: 30,
    sold: "yes",
    purchased_by: "Imran Bin Ali",
    title: "Studio Executive",
    size: "350",
    floor: "3rd Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioExecutive(350sqft).png",
  },
  {
    id: 28,
    sold: "yes",
    purchased_by: "Muhammad Saqib",
    title: "Studio Deluxe",
    size: "369",
    floor: "3rd Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioDeluxe(369sqft).png",
  },
  {
    id: 29,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "391",
    floor: "3rd Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/third/StudioDeluxe(391sqft).png",
  },
  {
    id: 26,
    sold: "no",
    purchased_by: "",
    title: "One Bed Executive",
    size: "575",
    floor: "3rd Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedExecutive(575sqft).png",
  },
  {
    id: 27,
    sold: "yes",
    purchased_by: "jehad Khan",
    title: "One Bed Executive",
    size: "593",
    floor: "3rd Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedExecutive(593sqft).png",
  },

  {
    id: 25,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "596",
    floor: "3rd Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/third/OneBedDeluxe(596sqft).png",
  },

  {
    id: 36,
    sold: "yes",
    purchased_by: "Amir Saeed",
    title: "Studio Executive",
    size: "350",
    floor: "4th Floor",
    number: "6",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioExecutive(350sqft).png",
  },
  {
    id: 34,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "369",
    floor: "4th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioDeluxe(369sqft).png",
  },
  {
    id: 35,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "391",
    floor: "4th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/StudioDeluxe(391sqft).png",
  },
  {
    id: 32,
    sold: "no",
    purchased_by: "",
    title: "One Bed Executive",
    size: "575",
    floor: "4th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedExecutive(575sqft).png",
  },
  {
    id: 33,
    sold: "no",
    purchased_by: "",
    title: "One Bed Executive",
    size: "593",
    floor: "4th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedExecutive(593sqft).png",
  },

  {
    id: 31,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "596",
    floor: "4th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/fourth/OneBedDeluxe(596sqft).png",
  },

  {
    id: 41,
    sold: "yes",
    purchased_by: "Faisal Shahid",
    title: "Studio Executive",
    size: "350",
    floor: "5th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/StudioExecutive(350sqft).png",
  },
  {
    id: 40,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "391",
    floor: "5th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/StudioDeluxe(391sqft).png",
  },
  {
    id: 39,
    sold: "no",
    purchased_by: "",
    title: "One Bed Executive",
    size: "575",
    floor: "5th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/OneBedExecutive(575sqft).png",
  },
  {
    id: 38,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "596",
    floor: "5th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/OneBedDeluxe(596sqft).png",
  },
  {
    id: 37,
    sold: "yes",
    purchased_by: "Rabia Waseem",
    title: "Two Bed Executive",
    size: "959",
    floor: "5th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/fifth/2BedExecutive(959sqft).png",
  },

  {
    id: 46,
    sold: "yes",
    purchased_by: "Muhammad Maisam",
    title: "Studio Executive",
    size: "350",
    floor: "6th Floor",
    number: "5",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/StudioExecutive(350sqft).png",
  },
  {
    id: 45,
    sold: "no",
    purchased_by: "",
    title: "Studio Deluxe",
    size: "391",
    floor: "6th Floor",
    number: "4",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/StudioDeluxe(391sqft).png",
  },
  {
    id: 44,
    sold: "yes",
    purchased_by: "Rao Shahrukh",
    title: "One Bed Executive",
    size: "575",
    floor: "6th Floor",
    number: "3",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/OneBedExecutive(575sqft).png",
  },
  {
    id: 43,
    sold: "no",
    purchased_by: "",
    title: "One Bed Deluxe",
    size: "596",
    floor: "6th Floor",
    number: "2",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/OneBedDeluxe(596sqft).png",
  },
  {
    id: 42,
    sold: "no",
    purchased_by: "",
    title: "Two Bed Executive",
    size: "959",
    floor: "6th Floor",
    number: "1",
    type: "Apartment",
    image: "/images/dsa/residences/sixth/2BedExecutive.png",
  },

  // end here
];

export function getAllResidences() {
  return residences;
}

export function getResidenceById(id) {
  return residences.find((item) => item.id === id);
}

export function getResidenceByType(type) {
  return residences.filter((item) => item.type === type);
}

export function getResidenceByFloor(floor) {
  return residences.filter((item) => item.floor === floor);
}
